### ISSUE TITLE
Working with moving QTreeInsertable objects.

### ISSUE THREAD

**Issue by achernetsky** [blackm00n/QTree-objc#1]
Hi,

QTree works cool with static QTreeInsertable annotations. But it fails if you need to move (change coordinate) annotation. Are you planning to add any QTree modifications methods (e.g. - (BOOL)removeObject:(id<QTreeInsertable>)object)?

**Comment by ram2386** [comment]
@achernetsky : Did it solve your issue ? Actually I am having a same issue and sometimes the pin is remove from the map while zoom in/out. If your problem is resolved then please give your feedback.
