### ISSUE TITLE
How to get list of objects in a cluster?

### ISSUE THREAD

**Issue by hyd00** [blackm00n/QTree-objc#7]
We can get number of objects count , in a cluster by `QCluster` `objectsCount` property. But how do I get a list of those objects?

Please help.

**Comment by blackm00n** [comment]
Will add possibility tomorrow

**Comment by hyd00** [comment]
Thank you so much! ... Waiting eagerly!

**Comment by hyd00** [comment]
Any updates Sir?

**Comment by blackm00n** [comment]
Hey @hyd00, check version 0.2, use `fillClusters` flag in `getObjectsInRegion:minNonClusteredSpan:fillClusters` method to get clusters with filled in `objects` property
